Repository Kusitms-29th-ASAP/Teacher, pull requests merged in 2024-05, with the labels that each got.

#7 [Feat] 알림장 kakao 공유하기 기능 구현
  .gitignore
  public/assets/images/teacher.svg
  src/app/classAnnouncement/page.tsx
  src/app/layout.tsx
  src/components/KakaoScript.tsx
Labels: feat

#12 [Fix] 1차 QA
  src/app/classAnnouncement/page.tsx
  src/components/common/Calendar.tsx
  src/components/common/Header.tsx
Labels: 🛠feat, 🔧fix

#15 [Feat] 알림장 추가 API 연동
  src/apis/authAxios.ts
  src/app/classAnnouncement/page.tsx
  src/components/common/Calendar.tsx
  src/components/common/Category.tsx
  src/components/common/Header.tsx
  src/components/common/ListItem.tsx
Labels: 🛠feat

#16 [Fix] 배포 오류
  src/components/common/Category.tsx
  src/components/common/GetItem.tsx
Labels: 🔧fix

#17 [Style] console.log 삭제
  src/apis/authAxios.ts
  src/app/classAnnouncement/page.tsx
  src/app/join/step1/page.tsx
  src/app/join/step2/page.tsx
  src/app/page.tsx
Labels: 🤝🏻style, 🔧fix

#18 [Fix] 배포 업데이트
  src/app/classAnnouncement/page.tsx
Labels: 🔧fix
